name: Python Package
on:
    push:
      branches: [ main ]
permissions:
  id-token: write
  contents: read

jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.8]
       steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: ${{matrix.python-version}}
        - uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            
 #       - uses: azure/login@v1
 #         with:
  #          creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 
        - name: python app.py
          run: |
            echo "Running app.py"
            python app.py
            echo "Finished running app.py"
